const XLSX = require('xlsx');

// Sample data for Gym_Database_services tab (service categories)
const servicesData = [
    { id: 1, name: 'Auto Services', type: 1, description: 'Repairs and maintenance for vehicles', isActive: true, isAvailable: true },
    { id: 2, name: 'Plumber Services', type: 2, description: 'Plumbing repairs and installations', isActive: true, isAvailable: true },
    { id: 3, name: 'Electrician Services', type: 3, description: 'Electrical repairs and installations', isActive: true, isAvailable: true },
    { id: 4, name: 'Carpenter Services', type: 4, description: 'Woodworking and carpentry', isActive: true, isAvailable: true },
    { id: 5, name: 'AC/Appliance Repair', type: 5, description: 'Repair of air conditioners and appliances', isActive: true, isAvailable: true },
    { id: 6, name: 'Car Rental', type: 6, description: 'Vehicle rental services', isActive: true, isAvailable: true },
    { id: 7, name: 'Tractor Rentals', type: 7, description: 'Tractor and equipment rental', isActive: true, isAvailable: true },
    { id: 8, name: 'Water Tank Supply', type: 8, description: 'Water supply and tank services', isActive: true, isAvailable: true },
    { id: 9, name: 'Home Interior Design', type: 9, description: 'Interior design services', isActive: false, isAvailable: false },
    { id: 10, name: 'Online Ticket Booking', type: 10, description: 'Bus ticket booking services', isActive: true, isAvailable: true }
];

// Sample data for services_details tab (providers)
const servicesDetailsData = [
    { id: 1, service_id: 1, name: 'Auto Kumar Workshop', phone: '+91 90000 12345', location: 'Gudiyatham Bus Stand', email: 'autokumar@example.com', website: '', rating: 4.5, description: 'Expert auto repairs and maintenance', opening_hours: '9 AM - 6 PM', services_offered: 'Engine repair, Oil change, Brake service', image: 'images/auto.svg', isActive: true, isAvailable: true },
    { id: 2, service_id: 1, name: 'Speedy Auto Care', phone: '+91 90000 12346', location: 'Main Road, Gudiyatham', email: 'speedyauto@example.com', website: 'www.speedyauto.com', rating: 4.2, description: 'Quick and reliable auto services', opening_hours: '8 AM - 8 PM', services_offered: 'Tire replacement, Battery check, Car wash', image: 'images/auto.svg', isActive: true, isAvailable: true },
    { id: 3, service_id: 1, name: 'Gudiyatham Auto Hub', phone: '+91 90000 12347', location: 'Station Road, Gudiyatham', email: 'autohub@example.com', website: '', rating: 4.0, description: 'Comprehensive auto repair services', opening_hours: '10 AM - 7 PM', services_offered: 'Engine tuning, Brake repair, Suspension', image: 'images/auto.svg', isActive: true, isAvailable: true },
    { id: 4, service_id: 1, name: 'Quick Fix Autos', phone: '+91 90000 12348', location: 'Old Market, Gudiyatham', email: 'quickfix@example.com', website: '', rating: 4.3, description: 'Fast and affordable auto repairs', opening_hours: '9 AM - 8 PM', services_offered: 'Oil change, Tire service, Diagnostics', image: 'images/auto.svg', isActive: true, isAvailable: true },
    { id: 5, service_id: 1, name: 'Reliable Auto Services', phone: '+91 90000 12349', location: 'Near Bus Stand, Gudiyatham', email: 'reliableauto@example.com', website: '', rating: 4.1, description: 'Trusted auto maintenance and repair', opening_hours: '8 AM - 6 PM', services_offered: 'Brake service, Engine repair, AC service', image: 'images/auto.svg', isActive: true, isAvailable: true },
    { id: 6, service_id: 1, name: 'Pro Auto Care', phone: '+91 90000 12350', location: 'Main Junction, Gudiyatham', email: 'proauto@example.com', website: '', rating: 4.4, description: 'Professional auto care services', opening_hours: '9 AM - 7 PM', services_offered: 'Full service, Parts replacement, Detailing', image: 'images/auto.svg', isActive: true, isAvailable: true },
    { id: 7, service_id: 2, name: 'Raja Plumber', phone: '+91 98765 43210', location: 'Old Pet, Gudiyatham', email: 'rajaplumber@example.com', website: '', rating: 4.0, description: 'Professional plumbing services', opening_hours: '7 AM - 9 PM', services_offered: 'Pipe repair, Leak fixing, Installation', image: 'images/plumber.svg', isActive: true, isAvailable: true },
    { id: 8, service_id: 2, name: 'Quick Plumb Services', phone: '+91 98765 43211', location: 'Market Area, Gudiyatham', email: 'quickplumb@example.com', website: '', rating: 4.2, description: 'Fast plumbing repairs', opening_hours: '8 AM - 8 PM', services_offered: 'Leak repair, Pipe installation, Drain cleaning', image: 'images/plumber.svg', isActive: true, isAvailable: true },
    { id: 9, service_id: 2, name: 'Expert Plumbing', phone: '+91 98765 43212', location: 'Central Gudiyatham', email: 'expertplumb@example.com', website: '', rating: 4.1, description: 'Expert plumbing solutions', opening_hours: '9 AM - 6 PM', services_offered: 'Water heater repair, Faucet fixing, Sewer line', image: 'images/plumber.svg', isActive: true, isAvailable: true },
    { id: 10, service_id: 2, name: 'Reliable Plumbers', phone: '+91 98765 43213', location: 'Near Hospital, Gudiyatham', email: 'reliableplumb@example.com', website: '', rating: 4.3, description: 'Reliable plumbing services', opening_hours: '7 AM - 7 PM', services_offered: 'Emergency repair, Installation, Maintenance', image: 'images/plumber.svg', isActive: true, isAvailable: true },
    { id: 11, service_id: 2, name: 'Pro Plumb Co.', phone: '+91 98765 43214', location: 'Industrial Area, Gudiyatham', email: 'proplumb@example.com', website: '', rating: 4.0, description: 'Professional plumbing company', opening_hours: '8 AM - 5 PM', services_offered: 'Commercial plumbing, Residential repair', image: 'images/plumber.svg', isActive: true, isAvailable: true },
    { id: 12, service_id: 2, name: 'Fix It Plumbing', phone: '+91 98765 43215', location: 'South Gudiyatham', email: 'fixitplumb@example.com', website: '', rating: 4.4, description: 'Quick plumbing fixes', opening_hours: '6 AM - 10 PM', services_offered: 'Leak detection, Pipe replacement, Fixture repair', image: 'images/plumber.svg', isActive: true, isAvailable: true },
    { id: 13, service_id: 3, name: 'Raja Electrician', phone: '+91 98765 43211', location: 'Old Pet, Gudiyatham', email: 'rajaelectric@example.com', website: '', rating: 4.3, description: 'Certified electrician services', opening_hours: '9 AM - 7 PM', services_offered: 'Wiring, Switch repair, Installation', image: 'images/electrician.svg', isActive: true, isAvailable: true },
    { id: 14, service_id: 3, name: 'Bright Sparks', phone: '+91 98765 43216', location: 'North Gate, Gudiyatham', email: 'brightsparks@example.com', website: '', rating: 4.1, description: 'Bright electrical services', opening_hours: '8 AM - 6 PM', services_offered: 'Rewiring, Outlet installation, Lighting', image: 'images/electrician.svg', isActive: true, isAvailable: true },
    { id: 15, service_id: 3, name: 'Power Electric', phone: '+91 98765 43217', location: 'Main Road, Gudiyatham', email: 'powerelectric@example.com', website: '', rating: 4.2, description: 'Power electrical solutions', opening_hours: '9 AM - 8 PM', services_offered: 'Fault diagnosis, UPS installation, Safety checks', image: 'images/electrician.svg', isActive: true, isAvailable: true },
    { id: 16, service_id: 3, name: 'Expert Electricians', phone: '+91 98765 43218', location: 'Central Market, Gudiyatham', email: 'expertel@example.com', website: '', rating: 4.0, description: 'Expert electrical work', opening_hours: '10 AM - 7 PM', services_offered: 'Home wiring, Commercial electrical, Repairs', image: 'images/electrician.svg', isActive: true, isAvailable: true },
    { id: 17, service_id: 3, name: 'Reliable Electric', phone: '+91 98765 43219', location: 'Near Bus Stand, Gudiyatham', email: 'reliableel@example.com', website: '', rating: 4.4, description: 'Reliable electrical services', opening_hours: '7 AM - 9 PM', services_offered: 'Emergency repair, Installation, Maintenance', image: 'images/electrician.svg', isActive: true, isAvailable: true },
    { id: 18, service_id: 3, name: 'Pro Electric Co.', phone: '+91 98765 43220', location: 'Industrial Area, Gudiyatham', email: 'proelectric@example.com', website: '', rating: 4.3, description: 'Professional electrical company', opening_hours: '8 AM - 5 PM', services_offered: 'Industrial wiring, Residential service', image: 'images/electrician.svg', isActive: true, isAvailable: true },
    { id: 19, service_id: 4, name: 'Raja Carpenter', phone: '+91 98765 43212', location: 'Old Pet, Gudiyatham', email: 'rajacarpenter@example.com', website: '', rating: 4.1, description: 'Custom woodworking and repairs', opening_hours: '10 AM - 6 PM', services_offered: 'Furniture making, Door repair, Cabinets', image: 'images/carpenter.svg', isActive: true, isAvailable: true },
    { id: 20, service_id: 4, name: 'Wood Works', phone: '+91 98765 43221', location: 'Wood Street, Gudiyatham', email: 'woodworks@example.com', website: '', rating: 4.2, description: 'Wood working specialists', opening_hours: '9 AM - 7 PM', services_offered: 'Custom furniture, Repairs, Installation', image: 'images/carpenter.svg', isActive: true, isAvailable: true },
    { id: 21, service_id: 4, name: 'Crafty Carpentry', phone: '+91 98765 43222', location: 'Market Area, Gudiyatham', email: 'craftycarp@example.com', website: '', rating: 4.0, description: 'Crafty carpentry services', opening_hours: '8 AM - 6 PM', services_offered: 'Door making, Cabinet repair, Flooring', image: 'images/carpenter.svg', isActive: true, isAvailable: true },
    { id: 22, service_id: 4, name: 'Expert Woodworkers', phone: '+91 98765 43223', location: 'Central Gudiyatham', email: 'expertwood@example.com', website: '', rating: 4.3, description: 'Expert woodworking', opening_hours: '10 AM - 5 PM', services_offered: 'Bespoke pieces, Repairs, Restoration', image: 'images/carpenter.svg', isActive: true, isAvailable: true },
    { id: 23, service_id: 4, name: 'Reliable Carpentry', phone: '+91 98765 43224', location: 'Near Hospital, Gudiyatham', email: 'reliablecarp@example.com', website: '', rating: 4.1, description: 'Reliable carpentry services', opening_hours: '9 AM - 7 PM', services_offered: 'Furniture repair, Installation, Custom work', image: 'images/carpenter.svg', isActive: true, isAvailable: true },
    { id: 24, service_id: 4, name: 'Pro Carpentry Co.', phone: '+91 98765 43225', location: 'Industrial Area, Gudiyatham', email: 'procarp@example.com', website: '', rating: 4.4, description: 'Professional carpentry company', opening_hours: '8 AM - 4 PM', services_offered: 'Commercial carpentry, Residential projects', image: 'images/carpenter.svg', isActive: true, isAvailable: true },
    { id: 25, service_id: 5, name: 'CoolTech Repairs', phone: '+91 98765 43213', location: 'Near Main Junction, Gudiyatham', email: 'cooltech@example.com', website: '', rating: 4.4, description: 'AC and appliance repair specialists', opening_hours: '8 AM - 8 PM', services_offered: 'AC repair, Fridge service, Washing machine', image: 'images/ac_repair.svg', isActive: true, isAvailable: true },
    { id: 26, service_id: 5, name: 'Chill Masters', phone: '+91 98765 43226', location: 'Main Road, Gudiyatham', email: 'chillmasters@example.com', website: '', rating: 4.2, description: 'AC repair experts', opening_hours: '9 AM - 7 PM', services_offered: 'AC installation, Repair, Maintenance', image: 'images/ac_repair.svg', isActive: true, isAvailable: true },
    { id: 27, service_id: 5, name: 'Appliance Pros', phone: '+91 98765 43227', location: 'Station Road, Gudiyatham', email: 'appliancepros@example.com', website: '', rating: 4.0, description: 'Appliance repair professionals', opening_hours: '10 AM - 6 PM', services_offered: 'Fridge repair, Washing machine service, Microwave', image: 'images/ac_repair.svg', isActive: true, isAvailable: true },
    { id: 28, service_id: 5, name: 'Cool Solutions', phone: '+91 98765 43228', location: 'Old Market, Gudiyatham', email: 'coolsolutions@example.com', website: '', rating: 4.3, description: 'Cooling solutions', opening_hours: '8 AM - 8 PM', services_offered: 'AC servicing, Appliance repair, Installation', image: 'images/ac_repair.svg', isActive: true, isAvailable: true },
    { id: 29, service_id: 5, name: 'Fix It Appliances', phone: '+91 98765 43229', location: 'Near Bus Stand, Gudiyatham', email: 'fixitapp@example.com', website: '', rating: 4.1, description: 'Appliance fixing services', opening_hours: '9 AM - 7 PM', services_offered: 'TV repair, AC gas refill, Fridge defrost', image: 'images/ac_repair.svg', isActive: true, isAvailable: true },
    { id: 30, service_id: 5, name: 'Pro Appliance Care', phone: '+91 98765 43230', location: 'Central Gudiyatham', email: 'proappcare@example.com', website: '', rating: 4.5, description: 'Professional appliance care', opening_hours: '7 AM - 9 PM', services_offered: 'All appliances, Emergency repair, Warranty service', image: 'images/ac_repair.svg', isActive: true, isAvailable: true },
    { id: 31, service_id: 6, name: 'Gudiyatham Car Rentals', phone: '+91 98765 43214', location: 'Station Road, Gudiyatham', email: 'carrental@example.com', website: '', rating: 4.6, description: 'Wide range of cars for rent', opening_hours: '24/7', services_offered: 'Car rental, Driver service, Long term lease', image: 'images/car_rental.svg', isActive: true, isAvailable: true },
    { id: 32, service_id: 6, name: 'Drive Easy', phone: '+91 98765 43231', location: 'Main Junction, Gudiyatham', email: 'driveeasy@example.com', website: '', rating: 4.4, description: 'Easy car rentals', opening_hours: '6 AM - 10 PM', services_offered: 'Sedan rental, SUV hire, Self-drive', image: 'images/car_rental.svg', isActive: true, isAvailable: true },
    { id: 33, service_id: 6, name: 'Rent a Ride', phone: '+91 98765 43232', location: 'Bus Stand, Gudiyatham', email: 'rentaride@example.com', website: '', rating: 4.2, description: 'Rent your ride', opening_hours: '24/7', services_offered: 'Car hire, Tempo rental, Driver included', image: 'images/car_rental.svg', isActive: true, isAvailable: true },
    { id: 34, service_id: 6, name: 'Quick Cars', phone: '+91 98765 43233', location: 'Old Pet, Gudiyatham', email: 'quickcars@example.com', website: '', rating: 4.0, description: 'Quick car rentals', opening_hours: '8 AM - 8 PM', services_offered: 'Daily rental, Weekly deals, Airport transfer', image: 'images/car_rental.svg', isActive: true, isAvailable: true },
    { id: 35, service_id: 6, name: 'Reliable Rentals', phone: '+91 98765 43234', location: 'Market Area, Gudiyatham', email: 'reliablerent@example.com', website: '', rating: 4.3, description: 'Reliable car rentals', opening_hours: '7 AM - 9 PM', services_offered: 'Luxury cars, Budget options, Corporate hire', image: 'images/car_rental.svg', isActive: true, isAvailable: true },
    { id: 36, service_id: 6, name: 'Pro Car Hire', phone: '+91 98765 43235', location: 'Central Gudiyatham', email: 'procarhire@example.com', website: '', rating: 4.5, description: 'Professional car hire', opening_hours: '24/7', services_offered: 'All types, Insurance included, 24/7 support', image: 'images/car_rental.svg', isActive: true, isAvailable: true },
    { id: 37, service_id: 7, name: 'Farmers Tractor Hire', phone: '+91 98765 43215', location: 'Outskirts, Gudiyatham', email: 'tractorhire@example.com', website: '', rating: 4.2, description: 'Tractor rentals with operators', opening_hours: '6 AM - 6 PM', services_offered: 'Tractor rental, Plowing, Harvesting equipment', image: 'images/tractor_rentals.svg', isActive: true, isAvailable: true },
    { id: 38, service_id: 7, name: 'Agri Tractors', phone: '+91 98765 43236', location: 'Farm Area, Gudiyatham', email: 'agritractors@example.com', website: '', rating: 4.0, description: 'Agricultural tractors', opening_hours: '5 AM - 7 PM', services_offered: 'Tractor hire, Implements, Operator service', image: 'images/tractor_rentals.svg', isActive: true, isAvailable: true },
    { id: 39, service_id: 7, name: 'Power Tractors', phone: '+91 98765 43237', location: 'Rural Gudiyatham', email: 'powertractors@example.com', website: '', rating: 4.3, description: 'Powerful tractor rentals', opening_hours: '6 AM - 6 PM', services_offered: 'Heavy duty tractors, Daily rental, Maintenance', image: 'images/tractor_rentals.svg', isActive: true, isAvailable: true },
    { id: 40, service_id: 7, name: 'Farm Equip Hire', phone: '+91 98765 43238', location: 'Near Fields, Gudiyatham', email: 'farmequip@example.com', website: '', rating: 4.1, description: 'Farm equipment hire', opening_hours: '7 AM - 5 PM', services_offered: 'Tractors, Harvesters, Plows', image: 'images/tractor_rentals.svg', isActive: true, isAvailable: true },
    { id: 41, service_id: 7, name: 'Reliable Tractors', phone: '+91 98765 43239', location: 'Outskirts, Gudiyatham', email: 'reliabletract@example.com', website: '', rating: 4.4, description: 'Reliable tractor services', opening_hours: '5 AM - 8 PM', services_offered: 'All farm work, Fuel included, Skilled operators', image: 'images/tractor_rentals.svg', isActive: true, isAvailable: true },
    { id: 42, service_id: 7, name: 'Pro Agri Rentals', phone: '+91 98765 43240', location: 'Agricultural Zone, Gudiyatham', email: 'proagri@example.com', website: '', rating: 4.2, description: 'Professional agricultural rentals', opening_hours: '6 AM - 6 PM', services_offered: 'Tractor fleet, Seasonal hire, Support services', image: 'images/tractor_rentals.svg', isActive: true, isAvailable: true },
    { id: 43, service_id: 8, name: 'Gudiyatham Water Supply', phone: '+91 98765 43216', location: 'Near Bus Stand, Gudiyatham', email: 'watersupply@example.com', website: '', rating: 4.0, description: 'Clean water supply services', opening_hours: '5 AM - 9 PM', services_offered: 'Water delivery, Tank cleaning, Borewell service', image: 'images/water_tank.svg', isActive: true, isAvailable: true },
    { id: 44, service_id: 8, name: 'Pure Water Supply', phone: '+91 98765 43241', location: 'Main Road, Gudiyatham', email: 'purewater@example.com', website: '', rating: 4.2, description: 'Pure water delivery', opening_hours: '6 AM - 8 PM', services_offered: 'Drinking water, Construction water, Tankers', image: 'images/water_tank.svg', isActive: true, isAvailable: true },
    { id: 45, service_id: 8, name: 'Aqua Supply', phone: '+91 98765 43242', location: 'Station Road, Gudiyatham', email: 'aquasupply@example.com', website: '', rating: 4.1, description: 'Aqua supply services', opening_hours: '7 AM - 7 PM', services_offered: 'Bulk water, Tank rental, Cleaning', image: 'images/water_tank.svg', isActive: true, isAvailable: true },
    { id: 46, service_id: 8, name: 'Water Masters', phone: '+91 98765 43243', location: 'Old Market, Gudiyatham', email: 'watermasters@example.com', website: '', rating: 4.3, description: 'Water supply masters', opening_hours: '5 AM - 10 PM', services_offered: 'Emergency supply, Regular delivery, Quality tested', image: 'images/water_tank.svg', isActive: true, isAvailable: true },
    { id: 47, service_id: 8, name: 'Reliable Water', phone: '+91 98765 43244', location: 'Near Hospital, Gudiyatham', email: 'reliablewater@example.com', website: '', rating: 4.0, description: 'Reliable water services', opening_hours: '6 AM - 9 PM', services_offered: 'Potable water, Non-potable, Tank maintenance', image: 'images/water_tank.svg', isActive: true, isAvailable: true },
    { id: 48, service_id: 8, name: 'Pro Water Supply', phone: '+91 98765 43245', location: 'Industrial Area, Gudiyatham', email: 'prowater@example.com', website: '', rating: 4.4, description: 'Professional water supply', opening_hours: '24/7', services_offered: 'All needs, Fast delivery, Competitive rates', image: 'images/water_tank.svg', isActive: true, isAvailable: true },
    { id: 49, service_id: 9, name: 'HomeStyle Interiors', phone: '+91 98765 43217', location: 'Central Market, Gudiyatham', email: 'homestyle@example.com', website: '', rating: 4.5, description: 'Complete interior design solutions', opening_hours: '10 AM - 7 PM', services_offered: 'Interior design, Painting, Modular kitchen', image: 'images/home_interior.svg', isActive: true, isAvailable: true },
    { id: 50, service_id: 9, name: 'Design Masters', phone: '+91 98765 43246', location: 'Main Road, Gudiyatham', email: 'designmasters@example.com', website: '', rating: 4.3, description: 'Interior design masters', opening_hours: '9 AM - 6 PM', services_offered: 'Home decor, Kitchen design, Painting', image: 'images/home_interior.svg', isActive: true, isAvailable: true },
    { id: 51, service_id: 9, name: 'Style Interiors', phone: '+91 98765 43247', location: 'Station Road, Gudiyatham', email: 'styleinteriors@example.com', website: '', rating: 4.1, description: 'Stylish interiors', opening_hours: '10 AM - 8 PM', services_offered: 'Modular furniture, Wall art, Lighting', image: 'images/home_interior.svg', isActive: true, isAvailable: true },
    { id: 52, service_id: 9, name: 'Creative Homes', phone: '+91 98765 43248', location: 'Old Market, Gudiyatham', email: 'creativehomes@example.com', website: '', rating: 4.4, description: 'Creative home designs', opening_hours: '9 AM - 7 PM', services_offered: 'Full interior, Renovation, Consultation', image: 'images/home_interior.svg', isActive: true, isAvailable: true },
    { id: 53, service_id: 9, name: 'Elegant Interiors', phone: '+91 98765 43249', location: 'Near Bus Stand, Gudiyatham', email: 'elegantint@example.com', website: '', rating: 4.2, description: 'Elegant interior solutions', opening_hours: '11 AM - 6 PM', services_offered: 'Luxury design, Budget options, Project management', image: 'images/home_interior.svg', isActive: true, isAvailable: true },
    { id: 54, service_id: 9, name: 'Pro Interior Design', phone: '+91 98765 43250', location: 'Central Gudiyatham', email: 'prointerior@example.com', website: '', rating: 4.5, description: 'Professional interior design', opening_hours: '10 AM - 7 PM', services_offered: 'End-to-end solutions, Quality materials, Expert team', image: 'images/home_interior.svg', isActive: true, isAvailable: true },
    { id: 55, service_id: 10, name: 'Gudiyatham Tickets', phone: '+91 98765 43251', location: 'Bus Stand, Gudiyatham', email: 'tickets@example.com', website: '', rating: 4.0, description: 'Bus ticket booking services', opening_hours: '6 AM - 10 PM', services_offered: 'Online booking, Counter service, Group tickets', image: 'images/ticket_booking.svg', isActive: true, isAvailable: true },
    { id: 56, service_id: 10, name: 'Quick Tickets', phone: '+91 98765 43252', location: 'Main Road, Gudiyatham', email: 'quicktickets@example.com', website: '', rating: 4.2, description: 'Quick ticket booking', opening_hours: '7 AM - 9 PM', services_offered: 'Bus tickets, Train reservations, Assistance', image: 'images/ticket_booking.svg', isActive: true, isAvailable: true },
    { id: 57, service_id: 10, name: 'Travel Bookers', phone: '+91 98765 43253', location: 'Station Road, Gudiyatham', email: 'travelbookers@example.com', website: '', rating: 4.1, description: 'Travel booking services', opening_hours: '8 AM - 8 PM', services_offered: 'All transport, Online portal, Customer support', image: 'images/ticket_booking.svg', isActive: true, isAvailable: true },
    { id: 58, service_id: 10, name: 'Easy Travel', phone: '+91 98765 43254', location: 'Old Market, Gudiyatham', email: 'easytravel@example.com', website: '', rating: 4.3, description: 'Easy travel bookings', opening_hours: '6 AM - 10 PM', services_offered: 'Bus, Train, Flight tickets, Packages', image: 'images/ticket_booking.svg', isActive: true, isAvailable: true },
    { id: 59, service_id: 10, name: 'Pro Bookings', phone: '+91 98765 43255', location: 'Near Hospital, Gudiyatham', email: 'probookings@example.com', website: '', rating: 4.0, description: 'Professional booking services', opening_hours: '9 AM - 7 PM', services_offered: 'Corporate bookings, Group travel, 24/7 support', image: 'images/ticket_booking.svg', isActive: true, isAvailable: true },
    { id: 60, service_id: 10, name: 'Reliable Tickets', phone: '+91 98765 43256', location: 'Central Gudiyatham', email: 'reliabletickets@example.com', website: '', rating: 4.4, description: 'Reliable ticket services', opening_hours: '24/7', services_offered: 'All modes, Instant booking, Cancellation support', image: 'images/ticket_booking.svg', isActive: true, isAvailable: true }
];

// Sample data for sales_categories tab
const salesCategoriesData = [
    { id: 1, name: 'Electronics', type: 'electronics', description: 'Electronic gadgets and appliances', isActive: true, isAvailable: true },
    { id: 2, name: 'Furniture', type: 'furniture', description: 'Home and office furniture', isActive: true, isAvailable: true },
    { id: 3, name: 'Clothing', type: 'clothing', description: 'Apparel and fashion items', isActive: false, isAvailable: false },
    { id: 4, name: 'Groceries', type: 'groceries', description: 'Food and household items', isActive: true, isAvailable: true },
    { id: 5, name: 'Automotive Parts', type: 'auto_parts', description: 'Car parts and accessories', isActive: true, isAvailable: true }
];

// Sample data for sales_details tab
const salesDetailsData = [
    { id: 1, category_type: 'electronics', name: 'Tech Hub Electronics', phone: '+91 90000 12347', location: 'Main Market, Gudiyatham', email: 'techhub@example.com', website: 'www.techhub.com', rating: 4.3, description: 'Latest electronics and gadgets', opening_hours: '10 AM - 8 PM', products: 'Phones, Laptops, TVs', image: 'images/electronics.jpeg', isActive: true, isAvailable: true },
    { id: 2, category_type: 'furniture', name: 'Comfort Furniture', phone: '+91 90000 12348', location: 'Furniture Street, Gudiyatham', email: 'comfort@example.com', website: '', rating: 4.1, description: 'Quality furniture for home', opening_hours: '9 AM - 7 PM', products: 'Sofas, Beds, Tables', image: 'images/furniture.jpeg', isActive: true, isAvailable: true },
    { id: 3, category_type: 'clothing', name: 'Fashion Corner', phone: '+91 90000 12349', location: 'Shopping Complex, Gudiyatham', email: 'fashion@example.com', website: '', rating: 4.0, description: 'Trendy clothing and accessories', opening_hours: '11 AM - 9 PM', products: 'Shirts, Pants, Shoes', image: 'images/clothing.jpeg', isActive: true, isAvailable: true },
    { id: 4, category_type: 'groceries', name: 'Fresh Mart', phone: '+91 90000 12350', location: 'Grocery Lane, Gudiyatham', email: 'freshmart@example.com', website: '', rating: 4.4, description: 'Fresh groceries and essentials', opening_hours: '6 AM - 10 PM', products: 'Vegetables, Fruits, Dairy', image: 'images/groceries.jpeg', isActive: true, isAvailable: true },
    { id: 5, category_type: 'auto_parts', name: 'Auto Parts Plus', phone: '+91 90000 12351', location: 'Auto Market, Gudiyatham', email: 'autoparts@example.com', website: '', rating: 4.2, description: 'Genuine auto parts and accessories', opening_hours: '8 AM - 6 PM', products: 'Tires, Batteries, Filters', image: 'images/auto_parts.jpeg', isActive: true, isAvailable: true }
];

// Create workbook
const wb = XLSX.utils.book_new();

// Add Gym_Database_services sheet
const wsServices = XLSX.utils.json_to_sheet(servicesData);
XLSX.utils.book_append_sheet(wb, wsServices, 'Gym_Database_services');

// Add services_details sheet
const wsDetails = XLSX.utils.json_to_sheet(servicesDetailsData);
XLSX.utils.book_append_sheet(wb, wsDetails, 'services_details');

// Add sales_categories sheet
const wsSalesCategories = XLSX.utils.json_to_sheet(salesCategoriesData);
XLSX.utils.book_append_sheet(wb, wsSalesCategories, 'sales_categories');

// Add sales_details sheet
const wsSalesDetails = XLSX.utils.json_to_sheet(salesDetailsData);
XLSX.utils.book_append_sheet(wb, wsSalesDetails, 'sales_details');

// Write to file
XLSX.writeFile(wb, 'Gym_Database.xlsx');

console.log('Gym_Database.xlsx created successfully!');
